## Creating Tensor CPU example

In [54]:
import torch
import numpy as np

first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
second_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])

add_tens = first_tens + second_tens
print(add_tens)
print(add_tens.size())
print(torch.__version__)
     

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])
2.5.1


In [55]:
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cpu


In [56]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


In [57]:
tens_a = torch.tensor([[10,11,12,13],[14,15,16,17]],device=device)
tens_b = torch.tensor([[18,19,20,21],[22,23,24,25]],device=device)
multi_tens = tens_a * tens_b
print(multi_tens)

tensor([[180, 209, 240, 273],
        [308, 345, 384, 425]])


## Moving Tensors Between CPUs and GPUs

In [58]:
# create a tensor
x = torch.tensor([5,10,15,10,25])
print("Tensor:", x)
# check tensor device (cpu/cuda)
print("Tensor device:", x.device)

Tensor: tensor([ 5, 10, 15, 10, 25])
Tensor device: cpu


In [59]:

print("CUDA GPU:", torch.cuda.is_available())
if torch.cuda.is_available():
   x = x.to("cuda:0")
   # or x=x.to("cuda")
print(x)

# now check the tensor device
print("Tensor device:", x.device)

CUDA GPU: False
tensor([ 5, 10, 15, 10, 25])
Tensor device: cpu


## Different ways to create tensors

In [60]:
# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])
# initialize a tensor from a tuple
tensor_from_tuple=torch.tensor((6,7,8,9,10))
print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])


In [61]:
# initialize a tensor from a ndarray
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_array)

Tensor from array: tensor([11, 12, 13, 14, 15])


## Different functions to create tensors:
torch.empty(), torch.ones(), and torch.zeros()

In [62]:
tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)
tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)
tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones)

tensor_emp : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [63]:
# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)
# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(4,5)
print("tensor_rand_norm :",tensor_rand_norm)
# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)

tensor_rand_un : tensor([[0.9052, 0.7638, 0.0861, 0.7896, 0.8809],
        [0.3287, 0.8112, 0.8220, 0.1723, 0.5826],
        [0.4876, 0.6861, 0.2431, 0.5658, 0.4786],
        [0.3697, 0.2279, 0.5374, 0.1425, 0.3797]])
tensor_rand_norm : tensor([[-2.9216, -0.7699, -0.4361, -0.9057,  1.2128],
        [-0.6430, -0.5445,  1.5387,  0.6093,  0.5031],
        [-1.8976, -1.3906, -0.0763, -1.2315,  0.5356],
        [-0.5510, -0.2058,  0.0304, -1.2532,  0.3939]])
tensor_rand_int : tensor([[9, 8, 7, 6, 5],
        [7, 5, 6, 5, 5],
        [6, 8, 8, 8, 6],
        [8, 7, 6, 6, 9]])


In [64]:
# initialize a tensor of ones
tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


## Tensor Attributes
knowing device location, datatype, dimension, and rank is very important

In [65]:
first_tensor = torch.tensor([1,2,3,4,5,6])

torch.device indicates the tensor’s device location

In [66]:
first_tensor.device

device(type='cpu')

torch.dtype indicates the tensor’s data type

In [67]:
first_tensor.dtype

torch.int64

torch.shape shows the tensor’s dimensions

In [68]:
first_tensor.shape

torch.Size([6])

torch.ndim identifies the number of a tensor’s dimensions or rank

In [69]:
first_tensor.ndim

1

In [70]:
second_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
second_tensor.dtype

torch.int64

In [72]:
second_tensor.shape

torch.Size([3, 3])

In [73]:
second_tensor.ndim

2

## Tensor Data Types

Integer data type tensor

In [74]:
#@title Integer data type tensor
int_tensor= torch.tensor([1,2,3,4,5],dtype=torch.int8)
int_tensor.dtype

torch.int8

Float data type tensor

In [75]:
float_tensor= torch.tensor([6,7,8,9,10], dtype=torch.float32)
float_tensor.dtype

torch.float32

Short data type tensor

In [76]:
short_tensor= torch.tensor([6,7,8,9,10], dtype=torch.int16)
short_tensor.dtype

torch.int16

Casting a tensor to a new data type (1st way)

In [77]:
int_tensor= int_tensor.float()
int_tensor.dtype

torch.float32

Casting a tensor to a new data type (2nd way)

In [78]:
last_tensor = short_tensor.to(dtype=torch.int8)
last_tensor.dtype

torch.int8

## Creating tensors from random samples

torch.rand() selects random values from a uniform distribution on the interval [0-1]

In [79]:
torch.manual_seed(111)
torch.rand(3, 3)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001],
        [0.9312, 0.2153, 0.6033]])

torch.rand() selects random values from a standard normal distribution

In [80]:
torch.rand(4,4)

tensor([[0.7328, 0.1857, 0.5101, 0.7545],
        [0.2884, 0.5775, 0.0358, 0.1026],
        [0.3419, 0.4400, 0.6341, 0.6224],
        [0.6334, 0.8580, 0.1572, 0.7853]])

torch.randint() selects random integers generated uniformly between specified low and high values

In [81]:
torch.randint(-1, 10, (3, 3))

tensor([[1, 0, 1],
        [5, 3, 1],
        [6, 7, 6]])

## Creating tensors like other tensors

Create a tensor of shape (2, 5) filled with ones

In [82]:
starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Create a tensor with the same size filled with random numbers

In [83]:
torch.manual_seed(111)
rand_tensor=torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

Create a tensor with the same shape filled with ones

In [84]:
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Create a tensor with the same shape filled with provided value

In [85]:
torch.full_like(starting_tensor,7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])

## Tensor Operations

Indexing 1-dim tensor example

In [86]:
one_dim_tensor=torch.tensor([1,2,3,4,5,6,7,8])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

tensor(3)
3


Slicing 1-dim tensor example
[start:end:step]

In [87]:
one_dim_tensor[1:4]

tensor([2, 3, 4])

Indexing 2-dim tensor example

In [88]:
two_dim_tensor=torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
two_dim_tensor[1][3]

tensor(10)

Slicing 2-dim tensor example

In [89]:
print("first three elements of the 1st row: ",two_dim_tensor[0, 0:3])
print("first four elements of the 2nd row: ",two_dim_tensor[1,0:4])

first three elements of the 1st row:  tensor([1, 2, 3])
first four elements of the 2nd row:  tensor([ 7,  8,  9, 10])


Use indexing to extract the data that meets some criteria

In [90]:
two_dim_tensor[two_dim_tensor<11]

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Combining tensors

In [91]:
torch.stack((two_dim_tensor, two_dim_tensor))

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]],

        [[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]])

Splitting tensors

In [92]:
first_tensor, second_tensor, third_tensor, fourth_tensor=torch.unbind(two_dim_tensor)
print(first_tensor, second_tensor, third_tensor, fourth_tensor)

tensor([1, 2, 3, 4, 5, 6]) tensor([ 7,  8,  9, 10, 11, 12]) tensor([13, 14, 15, 16, 17, 18]) tensor([19, 20, 21, 22, 23, 24])


Splitting 2-dim tensor

In [93]:
torch.unbind(two_dim_tensor,dim=1)

(tensor([ 1,  7, 13, 19]),
 tensor([ 2,  8, 14, 20]),
 tensor([ 3,  9, 15, 21]),
 tensor([ 4, 10, 16, 22]),
 tensor([ 5, 11, 17, 23]),
 tensor([ 6, 12, 18, 24]))

## Mathematical functions

Basic math functions

In [94]:
a=torch.tensor([10,2,8,6,4])
b=torch.tensor([1,2,4,3,1])
print('adding tensors and b:',a.add(b))
print('multiplying tensors and b:',a.mul(b))
print('dividing tensors and b:',a.div(b))

adding tensors and b: tensor([11,  4, 12,  9,  5])
multiplying tensors and b: tensor([10,  4, 32, 18,  4])
dividing tensors and b: tensor([10.,  1.,  2.,  2.,  4.])


Reduction functions

In [95]:
c = torch.tensor([[20., 14., 11., 8.], [3., 19., 14., 6.]])
print('Mean of the tensor c:',torch.mean(c))
print('Median of the tensor c:',torch.median(c))
print('Mode of the tensor c:',torch.mode(c))
print('Standard deviation of the tensor c:',torch.std(c))

Mean of the tensor c: tensor(11.8750)
Median of the tensor c: tensor(11.)
Mode of the tensor c: torch.return_types.mode(
values=tensor([8., 3.]),
indices=tensor([3, 0]))
Standard deviation of the tensor c: tensor(6.0341)


Linear algebra operations

PyTorch has a module called torch.linalg that contains a set of built-in linear algebra functions that are based on BLAS and LAPACK standardized libraries.

Compute the dot product (scalar) of two 1d tensors

In [96]:
first_tensor = torch.tensor([1,2,3])
second_tensor = torch.tensor([4,5,6])

dot_product = torch.matmul(first_tensor,second_tensor)
dot_product
     

tensor(32)

Compute the matrix-matrix product (2D tensor) of two 2d tensors

In [97]:
first_2d_tensor = torch.tensor([[1,2,3],[-1,-2,-3]])
second_2d_tensor = torch.tensor([[-1,-2],[4,5],[4,5]])

result_2d_tensor = torch.matmul(first_2d_tensor, second_2d_tensor)
result_2d_tensor

tensor([[ 19,  23],
        [-19, -23]])

Compute the a matrix product of 5 2d tensors

In [98]:
first_ten = torch.randn(2, 3)
second_ten = torch.randn(3, 4)
third_ten = torch.randn(4, 5)
fourth_ten = torch.randn(5, 6)
fifth_ten = torch.randn(6, 7)
torch.linalg.multi_dot((first_ten,second_ten,third_ten,fourth_ten,fifth_ten))

tensor([[ 56.3258,   5.6717,  26.5181, -16.0722,  -8.3279,  46.7059, -35.1574],
        [ 93.8132,  -2.7998,  60.6231, -12.8783, -26.6743,  53.9190, -39.4018]])

Computing eigenvalues and eigenvectors

In [99]:
# create a 3x3 square matrix
A = torch.randn(4,4)

# print the above created matrix
print("Matrix:", A)

# compute the Eigen values and vectors of the matrix
eigenvalues, eigenvectors = torch.linalg.eig(A)

print("Eigen Values:", eigenvalues)
print("Eigen Vectors:", eigenvectors)

Matrix: tensor([[-0.2644, -0.6944,  0.9034,  0.4772],
        [-0.2194, -1.1900,  0.0949, -0.5141],
        [ 0.9077, -1.6202, -0.7686, -1.0237],
        [ 0.4080,  1.3251,  0.1029, -1.2681]])
Eigen Values: tensor([ 0.5594+0.0000j, -1.8264+0.0000j, -1.1120+0.9959j, -1.1120-0.9959j])
Eigen Vectors: tensor([[-0.7994+0.0000j,  0.5558+0.0000j, -0.1600-0.1571j, -0.1600+0.1571j],
        [ 0.1080+0.0000j,  0.0307+0.0000j,  0.2757-0.2565j,  0.2757+0.2565j],
        [-0.5759+0.0000j, -0.7583+0.0000j,  0.7141+0.0000j,  0.7141-0.0000j],
        [-0.1326+0.0000j, -0.3393+0.0000j, -0.3386-0.4281j, -0.3386+0.4281j]])


## Automatic Differentiation (Autograd)

Define Tensor

In [100]:
x = torch.autograd.Variable(torch.Tensor([2]),requires_grad=True)
y = torch.autograd.Variable(torch.Tensor([1]),requires_grad=True)
z = torch.autograd.Variable(torch.Tensor([5]),requires_grad=True)

Compute gradients

In [101]:
# compute a
a = x - y

# define the function f
f = z * a
print("Final value for Function f = ",f)
#Compute gradients


f.backward()
#Print the gradient value
print("Gradient value for x:",x.grad)
print("Gradient value for y:",y.grad)
print("Gradient value for z:",z.grad)

Final value for Function f =  tensor([5.], grad_fn=<MulBackward0>)
Gradient value for x: tensor([5.])
Gradient value for y: tensor([-5.])
Gradient value for z: tensor([1.])


## Challenge